# Generated by Django 5.1.1 on 2024-11-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyoverview',
            options={'ordering': ['-week_start_date']},
        ),
    ]
